export const actionTypes = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  EVENTS: 'EVENTS',
  LOADING: 'LOADING',
  EMPLOYEE: 'EMPLOYEE',
  FLOWS: 'FLOWS',
  FORMS: 'FORMS',
  NODE: 'NODE',
  SUBS: 'SUB'
}   